// ISO 3166-1 country list with flag emojis and localized names
// Używane w nationality picker + passport issuing country
// Nazwy lokalne dodawane tylko dla top ~30 — reszta fallback na angielski

window.COUNTRIES = [
    { c: 'UA', n: 'Ukraine',       f: '🇺🇦', loc: { pl: 'Ukraina', uk: 'Україна', ru: 'Украина', hi: 'यूक्रेन' }, top: true },
    { c: 'BY', n: 'Belarus',       f: '🇧🇾', loc: { pl: 'Białoruś', uk: 'Білорусь', ru: 'Беларусь', hi: 'बेलारूस' }, top: true },
    { c: 'RU', n: 'Russia',        f: '🇷🇺', loc: { pl: 'Rosja', uk: 'Росія', ru: 'Россия', hi: 'रूस' }, top: true },
    { c: 'IN', n: 'India',         f: '🇮🇳', loc: { pl: 'Indie', uk: 'Індія', ru: 'Индия', hi: 'भारत' }, top: true },
    { c: 'NP', n: 'Nepal',         f: '🇳🇵', loc: { pl: 'Nepal', uk: 'Непал', ru: 'Непал', hi: 'नेपाल' }, top: true },
    { c: 'BD', n: 'Bangladesh',    f: '🇧🇩', loc: { pl: 'Bangladesz', uk: 'Бангладеш', ru: 'Бангладеш', hi: 'बांग्लादेश' }, top: true },
    { c: 'PK', n: 'Pakistan',      f: '🇵🇰', loc: { pl: 'Pakistan', uk: 'Пакистан', ru: 'Пакистан', hi: 'पाकिस्तान' }, top: true },
    { c: 'VN', n: 'Vietnam',       f: '🇻🇳', loc: { pl: 'Wietnam', uk: 'В\u0027єтнам', ru: 'Вьетнам', hi: 'वियतनाम' }, top: true },
    { c: 'PH', n: 'Philippines',   f: '🇵🇭', loc: { pl: 'Filipiny', uk: 'Філіппіни', ru: 'Филиппины', hi: 'फिलीपींस' }, top: true },
    { c: 'TR', n: 'Turkey',        f: '🇹🇷', loc: { pl: 'Turcja', uk: 'Туреччина', ru: 'Турция', hi: 'तुर्की' }, top: true },
    { c: 'GE', n: 'Georgia',       f: '🇬🇪', loc: { pl: 'Gruzja', uk: 'Грузія', ru: 'Грузия', hi: 'जॉर्जिया' }, top: true },
    { c: 'AM', n: 'Armenia',       f: '🇦🇲', loc: { pl: 'Armenia', uk: 'Вірменія', ru: 'Армения', hi: 'आर्मेनिया' }, top: true },
    { c: 'AZ', n: 'Azerbaijan',    f: '🇦🇿', loc: { pl: 'Azerbejdżan', uk: 'Азербайджан', ru: 'Азербайджан', hi: 'अज़रबैजान' }, top: true },
    { c: 'KZ', n: 'Kazakhstan',    f: '🇰🇿', loc: { pl: 'Kazachstan', uk: 'Казахстан', ru: 'Казахстан', hi: 'कज़ाख़िस्तान' }, top: true },
    { c: 'UZ', n: 'Uzbekistan',    f: '🇺🇿', loc: { pl: 'Uzbekistan', uk: 'Узбекистан', ru: 'Узбекистан', hi: 'उज़्बेकिस्तान' }, top: true },
    { c: 'MD', n: 'Moldova',       f: '🇲🇩', loc: { pl: 'Mołdawia', uk: 'Молдова', ru: 'Молдова', hi: 'मोल्दोवा' }, top: true },
    { c: 'CN', n: 'China',         f: '🇨🇳', loc: { pl: 'Chiny', uk: 'Китай', ru: 'Китай', hi: 'चीन' }, top: true },
    { c: 'EG', n: 'Egypt',         f: '🇪🇬', loc: { pl: 'Egipt', uk: 'Єгипет', ru: 'Египет', hi: 'मिस्र' }, top: true },
    { c: 'NG', n: 'Nigeria',       f: '🇳🇬', loc: { pl: 'Nigeria', uk: 'Нігерія', ru: 'Нигерия', hi: 'नाइजीरिया' }, top: true },
    { c: 'US', n: 'United States', f: '🇺🇸', loc: { pl: 'USA', uk: 'США', ru: 'США', hi: 'अमेरिका' }, top: true },
    { c: 'GB', n: 'United Kingdom',f: '🇬🇧', loc: { pl: 'Wielka Brytania', uk: 'Велика Британія', ru: 'Великобритания', hi: 'यूनाइटेड किंगडम' }, top: true },
    { c: 'DE', n: 'Germany',       f: '🇩🇪', loc: { pl: 'Niemcy', uk: 'Німеччина', ru: 'Германия', hi: 'जर्मनी' }, top: true },
    { c: 'IT', n: 'Italy',         f: '🇮🇹', loc: { pl: 'Włochy' } },
    { c: 'PL', n: 'Poland',        f: '🇵🇱', loc: { pl: 'Polska' }, top: true },
    // Rest of the world (alphabetical, English only — users will search)
    { c: 'AF', n: 'Afghanistan',   f: '🇦🇫' },
    { c: 'AL', n: 'Albania',       f: '🇦🇱' },
    { c: 'DZ', n: 'Algeria',       f: '🇩🇿' },
    { c: 'AD', n: 'Andorra',       f: '🇦🇩' },
    { c: 'AO', n: 'Angola',        f: '🇦🇴' },
    { c: 'AG', n: 'Antigua and Barbuda', f: '🇦🇬' },
    { c: 'AR', n: 'Argentina',     f: '🇦🇷' },
    { c: 'AU', n: 'Australia',     f: '🇦🇺' },
    { c: 'AT', n: 'Austria',       f: '🇦🇹' },
    { c: 'BS', n: 'Bahamas',       f: '🇧🇸' },
    { c: 'BH', n: 'Bahrain',       f: '🇧🇭' },
    { c: 'BB', n: 'Barbados',      f: '🇧🇧' },
    { c: 'BE', n: 'Belgium',       f: '🇧🇪' },
    { c: 'BZ', n: 'Belize',        f: '🇧🇿' },
    { c: 'BJ', n: 'Benin',         f: '🇧🇯' },
    { c: 'BT', n: 'Bhutan',        f: '🇧🇹' },
    { c: 'BO', n: 'Bolivia',       f: '🇧🇴' },
    { c: 'BA', n: 'Bosnia and Herzegovina', f: '🇧🇦' },
    { c: 'BW', n: 'Botswana',      f: '🇧🇼' },
    { c: 'BR', n: 'Brazil',        f: '🇧🇷' },
    { c: 'BN', n: 'Brunei',        f: '🇧🇳' },
    { c: 'BG', n: 'Bulgaria',      f: '🇧🇬' },
    { c: 'BF', n: 'Burkina Faso',  f: '🇧🇫' },
    { c: 'BI', n: 'Burundi',       f: '🇧🇮' },
    { c: 'KH', n: 'Cambodia',      f: '🇰🇭' },
    { c: 'CM', n: 'Cameroon',      f: '🇨🇲' },
    { c: 'CA', n: 'Canada',        f: '🇨🇦' },
    { c: 'CV', n: 'Cape Verde',    f: '🇨🇻' },
    { c: 'CF', n: 'Central African Republic', f: '🇨🇫' },
    { c: 'TD', n: 'Chad',          f: '🇹🇩' },
    { c: 'CL', n: 'Chile',         f: '🇨🇱' },
    { c: 'CO', n: 'Colombia',      f: '🇨🇴' },
    { c: 'KM', n: 'Comoros',       f: '🇰🇲' },
    { c: 'CG', n: 'Congo',         f: '🇨🇬' },
    { c: 'CD', n: 'Congo DRC',     f: '🇨🇩' },
    { c: 'CR', n: 'Costa Rica',    f: '🇨🇷' },
    { c: 'CI', n: 'Côte d\u0027Ivoire', f: '🇨🇮' },
    { c: 'HR', n: 'Croatia',       f: '🇭🇷' },
    { c: 'CU', n: 'Cuba',          f: '🇨🇺' },
    { c: 'CY', n: 'Cyprus',        f: '🇨🇾' },
    { c: 'CZ', n: 'Czechia',       f: '🇨🇿' },
    { c: 'DK', n: 'Denmark',       f: '🇩🇰' },
    { c: 'DJ', n: 'Djibouti',      f: '🇩🇯' },
    { c: 'DM', n: 'Dominica',      f: '🇩🇲' },
    { c: 'DO', n: 'Dominican Republic', f: '🇩🇴' },
    { c: 'EC', n: 'Ecuador',       f: '🇪🇨' },
    { c: 'SV', n: 'El Salvador',   f: '🇸🇻' },
    { c: 'GQ', n: 'Equatorial Guinea', f: '🇬🇶' },
    { c: 'ER', n: 'Eritrea',       f: '🇪🇷' },
    { c: 'EE', n: 'Estonia',       f: '🇪🇪' },
    { c: 'SZ', n: 'Eswatini',      f: '🇸🇿' },
    { c: 'ET', n: 'Ethiopia',      f: '🇪🇹' },
    { c: 'FJ', n: 'Fiji',          f: '🇫🇯' },
    { c: 'FI', n: 'Finland',       f: '🇫🇮' },
    { c: 'FR', n: 'France',        f: '🇫🇷' },
    { c: 'GA', n: 'Gabon',         f: '🇬🇦' },
    { c: 'GM', n: 'Gambia',        f: '🇬🇲' },
    { c: 'GH', n: 'Ghana',         f: '🇬🇭' },
    { c: 'GR', n: 'Greece',        f: '🇬🇷' },
    { c: 'GD', n: 'Grenada',       f: '🇬🇩' },
    { c: 'GT', n: 'Guatemala',     f: '🇬🇹' },
    { c: 'GN', n: 'Guinea',        f: '🇬🇳' },
    { c: 'GW', n: 'Guinea-Bissau', f: '🇬🇼' },
    { c: 'GY', n: 'Guyana',        f: '🇬🇾' },
    { c: 'HT', n: 'Haiti',         f: '🇭🇹' },
    { c: 'HN', n: 'Honduras',      f: '🇭🇳' },
    { c: 'HU', n: 'Hungary',       f: '🇭🇺' },
    { c: 'IS', n: 'Iceland',       f: '🇮🇸' },
    { c: 'ID', n: 'Indonesia',     f: '🇮🇩' },
    { c: 'IR', n: 'Iran',          f: '🇮🇷' },
    { c: 'IQ', n: 'Iraq',          f: '🇮🇶' },
    { c: 'IE', n: 'Ireland',       f: '🇮🇪' },
    { c: 'IL', n: 'Israel',        f: '🇮🇱' },
    { c: 'JM', n: 'Jamaica',       f: '🇯🇲' },
    { c: 'JP', n: 'Japan',         f: '🇯🇵' },
    { c: 'JO', n: 'Jordan',        f: '🇯🇴' },
    { c: 'KE', n: 'Kenya',         f: '🇰🇪' },
    { c: 'KI', n: 'Kiribati',      f: '🇰🇮' },
    { c: 'XK', n: 'Kosovo',        f: '🇽🇰' },
    { c: 'KW', n: 'Kuwait',        f: '🇰🇼' },
    { c: 'KG', n: 'Kyrgyzstan',    f: '🇰🇬' },
    { c: 'LA', n: 'Laos',          f: '🇱🇦' },
    { c: 'LV', n: 'Latvia',        f: '🇱🇻' },
    { c: 'LB', n: 'Lebanon',       f: '🇱🇧' },
    { c: 'LS', n: 'Lesotho',       f: '🇱🇸' },
    { c: 'LR', n: 'Liberia',       f: '🇱🇷' },
    { c: 'LY', n: 'Libya',         f: '🇱🇾' },
    { c: 'LI', n: 'Liechtenstein', f: '🇱🇮' },
    { c: 'LT', n: 'Lithuania',     f: '🇱🇹' },
    { c: 'LU', n: 'Luxembourg',    f: '🇱🇺' },
    { c: 'MG', n: 'Madagascar',    f: '🇲🇬' },
    { c: 'MW', n: 'Malawi',        f: '🇲🇼' },
    { c: 'MY', n: 'Malaysia',      f: '🇲🇾' },
    { c: 'MV', n: 'Maldives',      f: '🇲🇻' },
    { c: 'ML', n: 'Mali',          f: '🇲🇱' },
    { c: 'MT', n: 'Malta',         f: '🇲🇹' },
    { c: 'MH', n: 'Marshall Islands', f: '🇲🇭' },
    { c: 'MR', n: 'Mauritania',    f: '🇲🇷' },
    { c: 'MU', n: 'Mauritius',     f: '🇲🇺' },
    { c: 'MX', n: 'Mexico',        f: '🇲🇽' },
    { c: 'FM', n: 'Micronesia',    f: '🇫🇲' },
    { c: 'MC', n: 'Monaco',        f: '🇲🇨' },
    { c: 'MN', n: 'Mongolia',      f: '🇲🇳' },
    { c: 'ME', n: 'Montenegro',    f: '🇲🇪' },
    { c: 'MA', n: 'Morocco',       f: '🇲🇦' },
    { c: 'MZ', n: 'Mozambique',    f: '🇲🇿' },
    { c: 'MM', n: 'Myanmar',       f: '🇲🇲' },
    { c: 'NA', n: 'Namibia',       f: '🇳🇦' },
    { c: 'NR', n: 'Nauru',         f: '🇳🇷' },
    { c: 'NL', n: 'Netherlands',   f: '🇳🇱' },
    { c: 'NZ', n: 'New Zealand',   f: '🇳🇿' },
    { c: 'NI', n: 'Nicaragua',     f: '🇳🇮' },
    { c: 'NE', n: 'Niger',         f: '🇳🇪' },
    { c: 'KP', n: 'North Korea',   f: '🇰🇵' },
    { c: 'MK', n: 'North Macedonia', f: '🇲🇰' },
    { c: 'NO', n: 'Norway',        f: '🇳🇴' },
    { c: 'OM', n: 'Oman',          f: '🇴🇲' },
    { c: 'PW', n: 'Palau',         f: '🇵🇼' },
    { c: 'PS', n: 'Palestine',     f: '🇵🇸' },
    { c: 'PA', n: 'Panama',        f: '🇵🇦' },
    { c: 'PG', n: 'Papua New Guinea', f: '🇵🇬' },
    { c: 'PY', n: 'Paraguay',      f: '🇵🇾' },
    { c: 'PE', n: 'Peru',          f: '🇵🇪' },
    { c: 'PT', n: 'Portugal',      f: '🇵🇹' },
    { c: 'QA', n: 'Qatar',         f: '🇶🇦' },
    { c: 'RO', n: 'Romania',       f: '🇷🇴' },
    { c: 'RW', n: 'Rwanda',        f: '🇷🇼' },
    { c: 'KN', n: 'Saint Kitts and Nevis', f: '🇰🇳' },
    { c: 'LC', n: 'Saint Lucia',   f: '🇱🇨' },
    { c: 'VC', n: 'Saint Vincent and the Grenadines', f: '🇻🇨' },
    { c: 'WS', n: 'Samoa',         f: '🇼🇸' },
    { c: 'SM', n: 'San Marino',    f: '🇸🇲' },
    { c: 'ST', n: 'São Tomé and Príncipe', f: '🇸🇹' },
    { c: 'SA', n: 'Saudi Arabia',  f: '🇸🇦' },
    { c: 'SN', n: 'Senegal',       f: '🇸🇳' },
    { c: 'RS', n: 'Serbia',        f: '🇷🇸' },
    { c: 'SC', n: 'Seychelles',    f: '🇸🇨' },
    { c: 'SL', n: 'Sierra Leone',  f: '🇸🇱' },
    { c: 'SG', n: 'Singapore',     f: '🇸🇬' },
    { c: 'SK', n: 'Slovakia',      f: '🇸🇰' },
    { c: 'SI', n: 'Slovenia',      f: '🇸🇮' },
    { c: 'SB', n: 'Solomon Islands', f: '🇸🇧' },
    { c: 'SO', n: 'Somalia',       f: '🇸🇴' },
    { c: 'ZA', n: 'South Africa',  f: '🇿🇦' },
    { c: 'KR', n: 'South Korea',   f: '🇰🇷' },
    { c: 'SS', n: 'South Sudan',   f: '🇸🇸' },
    { c: 'ES', n: 'Spain',         f: '🇪🇸' },
    { c: 'LK', n: 'Sri Lanka',     f: '🇱🇰' },
    { c: 'SD', n: 'Sudan',         f: '🇸🇩' },
    { c: 'SR', n: 'Suriname',      f: '🇸🇷' },
    { c: 'SE', n: 'Sweden',        f: '🇸🇪' },
    { c: 'CH', n: 'Switzerland',   f: '🇨🇭' },
    { c: 'SY', n: 'Syria',         f: '🇸🇾' },
    { c: 'TW', n: 'Taiwan',        f: '🇹🇼' },
    { c: 'TJ', n: 'Tajikistan',    f: '🇹🇯' },
    { c: 'TZ', n: 'Tanzania',      f: '🇹🇿' },
    { c: 'TH', n: 'Thailand',      f: '🇹🇭' },
    { c: 'TL', n: 'Timor-Leste',   f: '🇹🇱' },
    { c: 'TG', n: 'Togo',          f: '🇹🇬' },
    { c: 'TO', n: 'Tonga',         f: '🇹🇴' },
    { c: 'TT', n: 'Trinidad and Tobago', f: '🇹🇹' },
    { c: 'TN', n: 'Tunisia',       f: '🇹🇳' },
    { c: 'TM', n: 'Turkmenistan',  f: '🇹🇲' },
    { c: 'TV', n: 'Tuvalu',        f: '🇹🇻' },
    { c: 'UG', n: 'Uganda',        f: '🇺🇬' },
    { c: 'AE', n: 'United Arab Emirates', f: '🇦🇪' },
    { c: 'UY', n: 'Uruguay',       f: '🇺🇾' },
    { c: 'VU', n: 'Vanuatu',       f: '🇻🇺' },
    { c: 'VA', n: 'Vatican City',  f: '🇻🇦' },
    { c: 'VE', n: 'Venezuela',     f: '🇻🇪' },
    { c: 'YE', n: 'Yemen',         f: '🇾🇪' },
    { c: 'ZM', n: 'Zambia',        f: '🇿🇲' },
    { c: 'ZW', n: 'Zimbabwe',      f: '🇿🇼' },
];

window.getCountryName = function(code, lang) {
    const country = window.COUNTRIES.find(c => c.c === code);
    if (!country) return code;
    return (country.loc && country.loc[lang]) || country.n;
};

window.searchCountries = function(query, lang) {
    const q = (query || '').toLowerCase().trim();
    if (!q) {
        // Return top countries first, then rest alphabetically
        const top = window.COUNTRIES.filter(c => c.top);
        const rest = window.COUNTRIES.filter(c => !c.top).sort((a, b) => a.n.localeCompare(b.n));
        return [...top, ...rest];
    }
    return window.COUNTRIES.filter(c => {
        const localName = (c.loc && c.loc[lang]) || '';
        return c.n.toLowerCase().includes(q) ||
               localName.toLowerCase().includes(q) ||
               c.c.toLowerCase() === q;
    });
};
