// Mock data for Getmypermit prototype
window.GMP_DATA = {
  company: {
    name: "Logistyka Wschód Sp. z o.o.",
    nip: "527-289-44-10",
    plan: "Pro",
    contact: "Anna Kowalska",
    avatar: "AK",
  },
  kpi: {
    total: 247,
    active: 218,
    onboarding: 14,
    offboarding: 8,
    nationalities: 12,
    redStatus: 7,
    yellowStatus: 23,
    greenStatus: 209,
    grayStatus: 8,
    expiring30: 18,
    expiring60: 31,
    expiring90: 52,
    overdue: 3,
    casesWithLawFirm: 11,
    pendingDocs: 34,
    riskScore: 86,
  },
  foreigners: [
    { id: "F-1042", name: "Oleksandr Tkachenko", nationality: "UA", flag: "🇺🇦", position: "Operator wózka widłowego", subcontractor: "FlexJob Sp. z o.o.", residenceStatus: "green", workStatus: "green", residenceDoc: "Karta pobytu czasowego", residenceExpiry: "2027-04-12", workDoc: "Zezwolenie typ A", workExpiry: "2027-04-12", riskLevel: "low", lastUpdate: "2026-04-28", events: 0, missing: 0 },
    { id: "F-1043", name: "Mariam Beridze", nationality: "GE", flag: "🇬🇪", position: "Pakowacz", subcontractor: "FlexJob Sp. z o.o.", residenceStatus: "green", workStatus: "yellow", residenceDoc: "Wiza krajowa D", residenceExpiry: "2026-08-30", workDoc: "Brak podstawy", workExpiry: null, riskLevel: "medium", lastUpdate: "2026-04-29", events: 1, missing: 1 },
    { id: "F-1044", name: "Hassan Akhtar", nationality: "PK", flag: "🇵🇰", position: "Magazynier", subcontractor: "Bezpośrednio", residenceStatus: "yellow", workStatus: "yellow", residenceDoc: "Wiza krajowa D", residenceExpiry: "2026-06-22", workDoc: "Oświadczenie", workExpiry: "2026-06-22", riskLevel: "medium", lastUpdate: "2026-04-25", events: 2, missing: 0 },
    { id: "F-1045", name: "Nguyễn Văn Minh", nationality: "VN", flag: "🇻🇳", position: "Operator linii produkcyjnej", subcontractor: "Trans-Personnel S.A.", residenceStatus: "red", workStatus: "red", residenceDoc: "Karta pobytu", residenceExpiry: "2026-04-15", workDoc: "Zezwolenie typ A", workExpiry: "2026-04-15", riskLevel: "high", lastUpdate: "2026-04-30", events: 3, missing: 2 },
    { id: "F-1046", name: "Daria Bondarenko", nationality: "UA", flag: "🇺🇦", position: "Kierowca C+E", subcontractor: "Bezpośrednio", residenceStatus: "green", workStatus: "green", residenceDoc: "PESEL UKR", residenceExpiry: "2026-09-30", workDoc: "Powiadomienie", workExpiry: "2026-09-30", riskLevel: "low", lastUpdate: "2026-04-30", events: 0, missing: 0 },
    { id: "F-1047", name: "Rajesh Kumar", nationality: "IN", flag: "🇮🇳", position: "Inżynier procesu", subcontractor: "Bezpośrednio", residenceStatus: "green", workStatus: "yellow", residenceDoc: "Niebieska Karta UE", residenceExpiry: "2028-01-15", workDoc: "Zmiana stanowiska", workExpiry: "2028-01-15", riskLevel: "medium", lastUpdate: "2026-04-22", events: 1, missing: 0 },
    { id: "F-1048", name: "Aleh Drazdou", nationality: "BY", flag: "🇧🇾", position: "Spawacz", subcontractor: "FlexJob Sp. z o.o.", residenceStatus: "yellow", workStatus: "green", residenceDoc: "Wiza krajowa D", residenceExpiry: "2026-05-30", workDoc: "Zezwolenie typ A", workExpiry: "2026-12-30", riskLevel: "medium", lastUpdate: "2026-04-30", events: 1, missing: 0 },
    { id: "F-1049", name: "Iryna Kovalenko", nationality: "UA", flag: "🇺🇦", position: "Pracownik biurowy", subcontractor: "Bezpośrednio", residenceStatus: "green", workStatus: "green", residenceDoc: "PESEL UKR", residenceExpiry: "2026-09-30", workDoc: "Powiadomienie", workExpiry: "2026-09-30", riskLevel: "low", lastUpdate: "2026-04-29", events: 0, missing: 0 },
    { id: "F-1050", name: "Mirjeta Krasniqi", nationality: "XK", flag: "🇽🇰", position: "Pakowacz", subcontractor: "Trans-Personnel S.A.", residenceStatus: "gray", workStatus: "gray", residenceDoc: "Brak danych", residenceExpiry: null, workDoc: "Brak danych", workExpiry: null, riskLevel: "unknown", lastUpdate: "2026-04-30", events: 0, missing: 4 },
    { id: "F-1051", name: "Volodymyr Shevchenko", nationality: "UA", flag: "🇺🇦", position: "Kierowca C+E", subcontractor: "Bezpośrednio", residenceStatus: "green", workStatus: "green", residenceDoc: "Karta pobytu czasowego", residenceExpiry: "2027-11-04", workDoc: "Zezwolenie typ A", workExpiry: "2027-11-04", riskLevel: "low", lastUpdate: "2026-04-27", events: 0, missing: 0 },
    { id: "F-1052", name: "Bayan Alibekov", nationality: "KZ", flag: "🇰🇿", position: "Magazynier", subcontractor: "FlexJob Sp. z o.o.", residenceStatus: "green", workStatus: "yellow", residenceDoc: "Wiza krajowa D", residenceExpiry: "2026-07-18", workDoc: "Oświadczenie wygasa", workExpiry: "2026-06-12", riskLevel: "medium", lastUpdate: "2026-04-28", events: 0, missing: 0 },
    { id: "F-1053", name: "Tetiana Lysenko", nationality: "UA", flag: "🇺🇦", position: "Kontroler jakości", subcontractor: "Bezpośrednio", residenceStatus: "green", workStatus: "green", residenceDoc: "Karta pobytu", residenceExpiry: "2028-03-22", workDoc: "Zezwolenie typ A", workExpiry: "2028-03-22", riskLevel: "low", lastUpdate: "2026-04-30", events: 0, missing: 0 },
  ],
  alerts: [
    { id: "A-001", severity: "overdue", title: "Karta pobytu wygasła", subject: "Nguyễn Văn Minh", subjectId: "F-1045", date: "2026-04-15", daysOffset: -16, message: "Dokument pobytowy wygasł 16 dni temu. Status czerwony — nie rekomendujemy dopuszczenia do pracy bez konsultacji kancelarii.", action: "Zleć kancelarii" },
    { id: "A-002", severity: "14", title: "Wiza kończy się za 13 dni", subject: "Aleh Drazdou", subjectId: "F-1048", date: "2026-05-14", daysOffset: 13, message: "Ustal czy cudzoziemiec będzie kontynuował pobyt i pracę w Polsce. Rekomendowane przygotowanie ścieżki legalizacyjnej.", action: "Otwórz kartę" },
    { id: "A-003", severity: "30", title: "Oświadczenie wygasa za 28 dni", subject: "Bayan Alibekov", subjectId: "F-1052", date: "2026-06-12", daysOffset: 28, message: "Brak nowej podstawy legalnej pracy po tej dacie. Dodaj zezwolenie albo zleć analizę.", action: "Otwórz kartę" },
    { id: "A-004", severity: "60", title: "Wiza kończy się za 52 dni", subject: "Hassan Akhtar", subjectId: "F-1044", date: "2026-06-22", daysOffset: 52, message: "Pora rozpocząć przygotowanie dokumentów. Możliwe scenariusze: przedłużenie wizy, karta pobytu czasowego, zezwolenie A.", action: "Zleć kancelarii" },
    { id: "A-005", severity: "missing", title: "Brak podstawy legalnej pracy", subject: "Mariam Beridze", subjectId: "F-1043", date: null, message: "Wprowadzono dane pobytowe, ale nie wskazano dokumentu uprawniającego do pracy. Przed dopuszczeniem dodaj zezwolenie/oświadczenie.", action: "Uzupełnij dokument" },
    { id: "A-006", severity: "60", title: "Wiza kończy się za 58 dni", subject: "Mariam Beridze", subjectId: "F-1043", date: "2026-08-30", daysOffset: 58, message: "Sprawdź ścieżkę kontynuacji pobytu i pracy.", action: "Otwórz kartę" },
    { id: "A-007", severity: "missing", title: "Brak danych — 4 pola", subject: "Mirjeta Krasniqi", subjectId: "F-1050", date: null, message: "Status szary. Brak: paszport, dokument pobytowy, podstawa pracy, data rozpoczęcia.", action: "Uzupełnij dane" },
    { id: "A-008", severity: "overdue", title: "Niepodjęcie pracy — 5 dni", subject: "Sample Worker", subjectId: "F-1099", date: "2026-04-26", daysOffset: -5, message: "Cudzoziemiec nie podjął pracy w terminie. Sprawdź obowiązek zawiadomienia organu.", action: "Zleć kancelarii" },
    { id: "A-009", severity: "30", title: "Zmiana wynagrodzenia", subject: "Rajesh Kumar", subjectId: "F-1047", date: "2026-05-15", daysOffset: 14, message: "Wprowadzono zmianę warunków pracy. Może to wpływać na legalność powierzenia pracy.", action: "Konsultacja" },
  ],
  events: [
    { id: "E-201", type: "praca-rozpoczeta", title: "Rozpoczęcie pracy", subject: "Daria Bondarenko", subjectId: "F-1046", date: "2026-04-30 08:14", status: "ok" },
    { id: "E-202", type: "wniosek-pobytowy", title: "Cudzoziemiec złożył wniosek pobytowy", subject: "Hassan Akhtar", subjectId: "F-1044", date: "2026-04-29 14:02", status: "todo", note: "Dodaj UPO" },
    { id: "E-203", type: "zmiana-warunkow", title: "Zmiana wynagrodzenia (+15%)", subject: "Rajesh Kumar", subjectId: "F-1047", date: "2026-04-28 11:30", status: "review" },
    { id: "E-204", type: "praca-zakonczona", title: "Zakończenie pracy", subject: "Former Employee", subjectId: "F-0987", date: "2026-04-26 17:00", status: "todo", note: "Sprawdź obowiązek zawiadomienia" },
    { id: "E-205", type: "upo", title: "UPO dostarczone", subject: "Hassan Akhtar", subjectId: "F-1044", date: "2026-04-25 10:18", status: "ok" },
    { id: "E-206", type: "praca-niepodjeta", title: "Niepodjęcie pracy", subject: "Sample Worker", subjectId: "F-1099", date: "2026-04-22 09:00", status: "review" },
  ],
  documents: [
    { id: "D-501", foreigner: "Oleksandr Tkachenko", foreignerId: "F-1042", type: "Karta pobytu czasowego", expiry: "2027-04-12", uploaded: "2025-04-12", status: "ok" },
    { id: "D-502", foreigner: "Oleksandr Tkachenko", foreignerId: "F-1042", type: "Zezwolenie na pracę typ A", expiry: "2027-04-12", uploaded: "2025-04-12", status: "ok" },
    { id: "D-503", foreigner: "Oleksandr Tkachenko", foreignerId: "F-1042", type: "Paszport", expiry: "2029-08-22", uploaded: "2025-04-12", status: "ok" },
    { id: "D-504", foreigner: "Mariam Beridze", foreignerId: "F-1043", type: "Wiza krajowa D", expiry: "2026-08-30", uploaded: "2025-08-30", status: "ok" },
    { id: "D-505", foreigner: "Mariam Beridze", foreignerId: "F-1043", type: "Podstawa legalnej pracy", expiry: null, uploaded: null, status: "missing" },
    { id: "D-506", foreigner: "Hassan Akhtar", foreignerId: "F-1044", type: "Wiza krajowa D", expiry: "2026-06-22", uploaded: "2025-06-22", status: "warning" },
    { id: "D-507", foreigner: "Hassan Akhtar", foreignerId: "F-1044", type: "Oświadczenie o powierzeniu pracy", expiry: "2026-06-22", uploaded: "2025-06-23", status: "warning" },
    { id: "D-508", foreigner: "Hassan Akhtar", foreignerId: "F-1044", type: "UPO — wniosek pobytowy", expiry: null, uploaded: "2026-04-25", status: "ok" },
    { id: "D-509", foreigner: "Nguyễn Văn Minh", foreignerId: "F-1045", type: "Karta pobytu", expiry: "2026-04-15", uploaded: "2025-04-15", status: "expired" },
    { id: "D-510", foreigner: "Nguyễn Văn Minh", foreignerId: "F-1045", type: "Zezwolenie na pracę typ A", expiry: "2026-04-15", uploaded: "2025-04-15", status: "expired" },
    { id: "D-511", foreigner: "Bayan Alibekov", foreignerId: "F-1052", type: "Oświadczenie o powierzeniu pracy", expiry: "2026-06-12", uploaded: "2025-06-12", status: "warning" },
    { id: "D-512", foreigner: "Mirjeta Krasniqi", foreignerId: "F-1050", type: "Paszport", expiry: null, uploaded: null, status: "missing" },
  ],
  subcontractors: [
    { id: "S-01", name: "FlexJob Sp. z o.o.", nip: "527-100-22-33", workers: 87, green: 71, yellow: 12, red: 2, gray: 2, lastSync: "2026-04-30 09:00", contact: "Marek Wiśniewski", status: "active" },
    { id: "S-02", name: "Trans-Personnel S.A.", nip: "118-002-44-55", workers: 54, green: 42, yellow: 8, red: 3, gray: 1, lastSync: "2026-04-29 16:42", contact: "Joanna Lewicka", status: "active" },
    { id: "S-03", name: "Bezpośrednio (LW)", nip: "527-289-44-10", workers: 106, green: 96, yellow: 8, red: 2, gray: 0, lastSync: "—", contact: "Anna Kowalska", status: "internal" },
    { id: "S-04", name: "Praca Plus 24", nip: "899-302-11-08", workers: 0, green: 0, yellow: 0, red: 0, gray: 0, lastSync: "Zaproszono", contact: "—", status: "invited" },
  ],
  cases: [
    { id: "C-2026-031", title: "Karta pobytu wygasła — analiza ryzyka", foreigner: "Nguyễn Văn Minh", foreignerId: "F-1045", opened: "2026-04-30", lawyer: "mec. P. Zieliński", stage: "W toku", priority: "high", lastUpdate: "2026-04-30 13:20" },
    { id: "C-2026-030", title: "Niepodjęcie pracy — obowiązek zawiadomienia", foreigner: "Sample Worker", foreignerId: "F-1099", opened: "2026-04-26", lawyer: "mec. M. Antoniak", stage: "Czeka na dokumenty", priority: "medium", lastUpdate: "2026-04-29 10:00" },
    { id: "C-2026-029", title: "Zmiana warunków pracy — ocena dopuszczalności", foreigner: "Rajesh Kumar", foreignerId: "F-1047", opened: "2026-04-28", lawyer: "mec. P. Zieliński", stage: "Analiza", priority: "medium", lastUpdate: "2026-04-30 09:14" },
    { id: "C-2026-028", title: "Wiza — przygotowanie ścieżki legalizacji", foreigner: "Hassan Akhtar", foreignerId: "F-1044", opened: "2026-04-22", lawyer: "mec. K. Nowak", stage: "Wniosek przygotowany", priority: "low", lastUpdate: "2026-04-29 16:05" },
    { id: "C-2026-026", title: "Audyt podwykonawcy FlexJob — Q2", foreigner: "—", foreignerId: null, opened: "2026-04-15", lawyer: "mec. M. Antoniak", stage: "W toku", priority: "medium", lastUpdate: "2026-04-28 12:00" },
  ],
  activity: [
    { time: "14:32", text: "System wykrył wygaśnięcie dokumentu", subject: "Nguyễn Văn Minh", icon: "warning-octagon", tone: "danger" },
    { time: "13:18", text: "Kancelaria zaktualizowała sprawę C-2026-031", subject: "mec. P. Zieliński", icon: "scales", tone: "info" },
    { time: "11:04", text: "Dodano dokument: UPO — wniosek pobytowy", subject: "Hassan Akhtar", icon: "file-arrow-up", tone: "ok" },
    { time: "10:21", text: "Podwykonawca FlexJob zsynchronizował 12 osób", subject: "FlexJob Sp. z o.o.", icon: "buildings", tone: "neutral" },
    { time: "09:47", text: "Zmieniono status pracy na żółty", subject: "Mariam Beridze", icon: "warning-circle", tone: "warning" },
    { time: "08:14", text: "Rozpoczęcie pracy — oznaczone", subject: "Daria Bondarenko", icon: "play-circle", tone: "ok" },
  ],
};
